### ISSUE TITLE
Port extension to Visual Studio 2019 

### ISSUE THREAD

**Issue by Simulacrux** [zeroc-ice/ice-builder-visualstudio#13]
Hello,

would it be possible to port this extension to the new Visual Studio 2019. 
This new Version was released early April and it would be great to get the needed extensions running for a switch.

I tried to do a port myself, but I'm unable to compile the whole extension because I'm missing the older Visual Studios on my machine. I would be very happy to alpha/beta test a new version.

Thanks in advance
Cheers Simulacrux

**Comment by pepone** [comment]
Yes, we have already tested with earlier 2019 betas, I will try with the new 2019 release and see how it goes.

You can test the previous beta https://github.com/zeroc-ice/ice-builder-visualstudio/releases/tag/v6.0.0-beta0

**Comment by Simulacrux** [comment]
Hi,

I downloaded the beta version and tried it to install in the newest release of Visual Studio 2019 (16.1.1) but it says, that no matching version is found. I attached the log file of the installation attempt.
I think the lines with 
```
04.06.2019 16:46:10 - 	Supported Products : 
04.06.2019 16:46:10 - 		Microsoft.VisualStudio.Pro
04.06.2019 16:46:10 - 			Version : [14.0,16.0]
```
are the problem, because VS 2019 is already 16.1

Cheers Simulacrux

[dd_VSIXInstaller_20190604164607.log](https://github.com/zeroc-ice/ice-builder-visualstudio/files/3252996/dd_VSIXInstaller_20190604164607.log)

**Comment by pepone** [comment]
I will upload a new later today, the manifest didn't support 16.1

**Comment by pepone** [comment]
I just uploaded 6.0 with support for Visual Studio 2019 see https://github.com/zeroc-ice/ice-builder-visualstudio/releases/tag/v6.0.0

It is now also available in the marketplace https://marketplace.visualstudio.com/items?itemName=ZeroCInc.IceBuilder

**Comment by Simulacrux** [comment]
Thank you, I tested the new version and it is working now as expected :)
