### ISSUE TITLE
Visual Studio 2019 crashes while Project Upgrade

### ISSUE THREAD

**Issue by Simulacrux** [zeroc-ice/ice-builder-visualstudio#16]
Hello,

I currently try to move from VS2015 to VS2019 and from IceBuilder 4.3.10 to 6.0.0. 
After I try to open an Ice related solution, the Ice Builder is prompting me following dialog.
![image](https://user-images.githubusercontent.com/12858171/68773338-ae8c1d80-062b-11ea-9f0b-6525f7b5990e.png)
If I accept this offer some wait cursor spinning is applied and after a couple of seconds, the whole Visual Studio 2019 crashes (no other prompt, no error message). Right away it restarts and tries to load the last solution again. Then he discovers this solution must be converted and prompts me the same dialog again. 
If I accept, I go into a never ending loop. A cancel is breaking it, but nothing is converted and the solution is not compile able, because the Ice related projects giving me following error:

> This project requires the Ice Builder for Visual Studio extension. Use "Tools &gt; Extensions and Updates" to install it. For more information, see https://visualstudiogallery.msdn.microsoft.com/1a64e701-63f2-4740-8004-290e6c682ce0.

A look into the Event-Viewer from Windows the 4 messages I attached are related to the VS2019 crash.
[DevEnvFail.zip](https://github.com/zeroc-ice/ice-builder-visualstudio/files/3841749/DevEnvFail.zip)

Our solution is under TFS source control and checked in at the start of the whole process.
The Visual Studio (patch 16.3.4) is running on a Windows 10 1903 patched to the last released CU version.

Could you verify this behavior? Or am I doing something wrong on our side?

Best Regards,
Simulacrux

**Comment by bernardnormier** [comment]
Did you try to perform this upgrade from IceBuilder 4.3 to 6.0 in Visual Studio 2015? Are you converting C++ or C# projects?

**Comment by Simulacrux** [comment]
Hi,

no I currently did not test it on a VS2015 machine, because our new VMs only have VS2019 installed. But I could try to switch around my working VS2015 with 4.3 to a 6.0 version.
We are trying to convert C# projects.

Best Regards,
Simulacrux

**Comment by pepone** [comment]
Hi Simulacrux,

I was able to reproduce the issue, it is a problem with reloading the project from a background thread after it is updated.

[IceBuilder.zip](https://github.com/zeroc-ice/ice-builder-visualstudio/files/3847894/IceBuilder.zip)

Can you test with the attached vsix package, you will have to first uninstall the Ice Builder extension extract the zip archive and install new extension using the vsix file.

**Comment by Simulacrux** [comment]
Hi Pepone,
I tested the new version in our VMs and the conversion is now working and doing a correct update of the solutions. Our Projects are also building after the load and using the "new" ice.msbuild packages.

Best Regards,
Simulacrux

**Comment by pepone** [comment]
Fixed in 6.0.1 release
