### ISSUE TITLE
Cloned project fails when building

### ISSUE THREAD

**Issue by bruce987** [zeroc-ice/ice-builder-visualstudio#17]
I did a clone of the project and loaded it into VS2019 16.7.1 (latest as of today). Here are the errors...
![image](https://user-images.githubusercontent.com/1581231/90544019-20aa0980-e14c-11ea-8d2e-75a2ea895976.png)

**Comment by pepone** [comment]
I just push a fix for IceBuilder_VS2017 dependencies, did you install all the build requirements? see https://github.com/zeroc-ice/ice-builder-visualstudio#build-requirements

Seems the errors are due to some missing references listed in the warnings
