### ISSUE TITLE
compiling failed

### ISSUE THREAD

**Issue by Asiatelco** [zeroc-ice/ice-builder-visualstudio#18]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3245: 未能解析此引用。未能找到程序集“Microsoft.VisualStudio.Shell.12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。
1>D:\ice-demos\ice-builder-visualstudio\IceBuilder_Common\IVsProjectExtension.cs(42,39,42,50): error CS0103: 当前上下文中不存在名称“VSConstants”
1>D:\ice-demos\ice-builder-visualstudio\IceBuilder_Common\IVsProjectExtension.cs(64,13,64,25): error CS0103: 当前上下文中不存在名称“ErrorHandler”
1>D:\ice-demos\ice-builder-visualstudio\IceBuilder_Common\IVsProjectExtension.cs(64,63,64,74): error CS0103: 当前上下文中不存在名称“VSConstants”
1>D:\ice-demos\ice-builder-visualstudio\IceBuilder_Common\IVsProjectExtension.cs(73,17,73,29): error CS0103: 当前上下文中不存在名称“ErrorHandler”
1>D:\ice-demos\ice-builder-visualstudio\IceBuilder_Common\IVsProjectExtension.cs(73,67,73,78): error CS0103: 当前上下文中不存在名称“VSConstants”
1>D:\ice-demos\ice-builder-visualstudio\IceBuilder_Common\IVsProjectExtension.cs(93,21,93,33): error CS0103: 当前上下文中不存在名称“ErrorHandler”
1>D:\ice-demos\ice-builder-visualstudio\IceBuilder_Common\IVsProjectExtension.cs(93,75,93,86): error CS0103: 当前上下文中不存在名称“VSConstants”
1>D:\ice-demos\ice-builder-visualstudio\IceBuilder_Common\IVsProjectExtension.cs(272,13,272,25): error CS0103: 当前上下文中不存在名称“ErrorHandler”

**Comment by pepone** [comment]
You should try with Visual Studio 2019

**Comment by Asiatelco** [comment]
thx&nbsp;



发自我的iPhone


------------------ Original ------------------
