### ISSUE TITLE
Checkout of all C# project files in TFS

### ISSUE THREAD

**Issue by Simulacrux** [zeroc-ice/ice-builder-visualstudio#5]
Hello,

if you are open up an solution in the VisualStudio, the newest Ice Builder for VisualStudio is checking out every .csproj file from the TFS. This happens also if no IceBuilder is even configured in the whole solution. It is not a major error, because the files are not change in any kind of way, but normally a solution should open up without any checkouts.
I think it has something to do with the conversion attempt from old Builder notation in the files to the new one, but this only should be done if there is an conversion necessary and not every single day and with projects which are not using Ice at all.

Best Regards
Simulacrux

**Comment by pepone** [comment]
Hi,

I have a fix for this will you be able to test the attached VSIX package to ensure it works fine in your use case.


[IceBuilder.zip](https://github.com/zeroc-ice/ice-builder-visualstudio/files/2488744/IceBuilder.zip)

Cheers,
José

**Comment by Simulacrux** [comment]
Hi,
sorry for the late response.

I tried to test your VSIX today, but I could not manage it to install in our Visual Studio 2015. It seems bound to Visual Studio 2013 only? At least every attempt of installation is providing only the possibility for 2013. Is there something off with the supported version in manifest in this particular build?

Cheers,
Simulacrux

**Comment by pepone** [comment]
Hi,

Try to uninstall the previous version in Visual Studio 2015 first

**Comment by Simulacrux** [comment]
Hello,

my bad, that was the problem. Now I could give the test version a quick dry run. 
In a Solution without Ice, nothing is checked out anymore.
And a solution with an old 4 syntax in it, it overs correctly the upgrade dialog and then checks out only the needed project file and adds the new nuget package and ice msbuild syntax in it. 
Seems to work good.

THX for the fix. 
Cheers,
Simulacrux

**Comment by pepone** [comment]
Hi,

Thanks for taking the time to check this out, it will be part of the next release.

Cheers,
José
