### ISSUE TITLE
Include Slice syntax highlighting (TextMate grammar) in extension

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice-builder-visualstudio#6]
The next release of the Ice Builder for Visual Studio extension should include Slice syntax highlighting. See:
https://github.com/zeroc-ice/vscode-slice
https://msdn.microsoft.com/en-us/library/mt742400.aspx

**Comment by pepone** [comment]
Currently our extension installation relies on VSIX and that is just a ZIP that VS uncompressed to the extensions directory and register with VS, VSIX doesn't provide a way to install external files, if we want to do that the extension will have to include the text grammar as a resource and copy it to the required directory upon start.

**Comment by Simulacrux** [comment]
Hi,

just for documentation until this enhancement is included in the extension and other guys are trying to get it to work.

You could copy the `ice.tmLanguage.json` file in a folder structure like `ice\syntaxes` under your user profile `%userprofile%\.vs\Extensions` to get it working in Visual Studio.

Cheers Simulacrux
